name: Deploy Site on push
on:
  workflow_dispatch:
  push:
    branches:
      - main 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run npm install
        run: npm install 
      - name: Build site 
        run: npm run build
      - name: Create SSH key
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
      - name: Add Known Hosts 
        run: ssh-keyscan -t rsa "${{ secrets.HOST }}" >> ~/.ssh/known_hosts 
      - name: Deploy to site1 with rsync
        run: rsync -rav --delete ${{ github.workspace }}/dist/ "${{ secrets.USER }}"@${{ secrets.HOST }}:~/electrictestgarden.com/babayaga
      - name: Deploy to site2 with rsync
        run: rsync -rav --delete ${{ github.workspace }}/dist/ "${{ secrets.USER }}"@${{ secrets.HOST }}:~/${{ secrets.WEBSITE }}/babayaga
      